---
title: "genie_regulonES"
output: html_document
---

# loading libraries
```{r}
library(data.table)
library(Seurat)
library(hdf5r)
library(dplyr)
library(tibble)
library(viper)
library(pheatmap)
```

# prepping the data

## read in the expression matrix (Xenium dataset)
```{r}
# Read the HDF5 file
sce <- Read10X_h5("xenium_output/cell_feature_matrix.h5")

# Access the expression matrix
expr <- as.matrix(sce$`Gene Expression`)

dim(expr)
# Make sure gene names are rownames
expr[1:6, 1:6]
```

## read in the genie3 network and extract regulons 

```{r}
# Load the regulon table
regulon_df <- fread("GENIE3/BRCA/genie3_BRCA_mrn.top_100k.csv")

# list of regulons (= named list of weights, names are regulators)
regulon_list <- regulon_df %>%
  group_by(regulatoryGene) %>%
  summarize(regulon = list(setNames(weight, targetGene))) %>%
  deframe()
```

check gene names
```{r}
target_genes <- unique(regulon_df$targetGene)
common_genes <- intersect(rownames(expr), target_genes)

nrow(expr)
length(target_genes)
length(common_genes)
```

## read in the sponge network and extract miRNA modules

```{r}
# Load the ceRNA table
ceRNA_mod_df <- fread("SPONGE/breast_invasive_carcinoma/breast_invasive_carcinoma_interactionNetwork.csv")


```


# calculating the scores

## Regulon ES

viper

```{r}
# transform the regulon list
regulon_viper <- lapply(regulon_list, function(targets) {
  list(tfmode = targets, likelihood = abs(targets)) # ???
})


# Run VIPER using the expression matrix and regulon
vpres <- viper(expr, regulon_viper, method = "scale")

# vpres is a matrix: TFs × cells/spots
head(vpres[, 1:5])
```

```{r}
write.csv(vpres, "regulons_vpres_matrix.csv")
pheatmap(vpres[, 1:100])
```
