---
title: "testing"
output: html_document
---

```{r}
library(Matrix)
library(data.table)
library(viper)

source("./utils.R")
```

```{r}
# Read metadata
var <- fread("../datasets_scores/GSM6592049_M2_prepro/var.csv")

# Read sparse matrix
X <- readMM("../datasets_scores/GSM6592049_M2_prepro/expr.mtx")
rownames(X) <- fread("../datasets_scores/GSM6592049_M2_prepro/cells.txt", header = FALSE)$V1
colnames(X) <- var[,V1]
expr <- t(as.matrix(X))
```

```{r}
nrow(regulon_df)

regulon_df %>%
  arrange(weight) %>%
  head(100000)

```


```{r}
# Read regulon file
regulon_df <- fread("../networks/GENIE3/BRCA/genie3_BRCA_mrn.top_100k.csv")
vregulons <- create_Genie_modules(regulon_df, expr, 100000, ".", 20, 20)
  
regulons <- lapply(vregulons, function(x) names(x$tfmode))
```



```{r}
ceRNA_interactions <- fread("../networks/SPONGE/breast_invasive_carcinoma/breast_invasive_carcinoma_interactionNetwork.csv")
ceRNA_centralities <- fread("../networks/SPONGE/breast_invasive_carcinoma/breast_invasive_carcinoma_networkAnalysis.csv")

modules <- create_Sponge_modules(var, ceRNA_interactions, ceRNA_centralities, mscor=0.1, padj=0.05, feature_col='feature_type', RNAs=c("lncRNA","protein_coding"), ensembl_col="ensembl_ids", n_modules, n_cores)

```


```{r}
# Initialize empty matrix
n <- length(regulons)
overlap_mat <- matrix(0, nrow = n, ncol = n,
                      dimnames = list(names(regulons), names(regulons)))

# Fill in with intersection sizes
for (i in seq_len(n)) {
  for (j in seq_len(n)) {
    overlap_mat[i, j] <- length(intersect(regulons[[i]], regulons[[j]]))/length(regulons[[i]])
  }
}

overlap_mat
```

```{r}
apply(overlap_mat, 1, function(x) sum(x>0))
```

